export const CATEGORY_SELECTED = "CATEGORY_SELECTED";
export const LOCATION_SELECTED = "LOCATION_SELECTED";
export const VEHICLE_SELECTED = "VEHICLE_SELECTED";
export const DATE_SELECTED = "DATE_SELECTED";
export const ITEMS_SAVED = "ITEMS_SAVED";
export const CONTACT_INFO_SAVED = "CONTACT_INFO_SAVED";
export const SET_STEP = "SET_STEP";
